version: 0.2
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      - export PATH="$PATH:$HOME/.dotnet"
      - export DOTNET_ROOT="$HOME/.dotnet"
  build:
    commands:
      # Команда publish автоматично робить і restore, і build
      - dotnet publish -c Release -o ./publish_output AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      # Створюємо Procfile у папці з готовим кодом і примусово задаємо порт 5000
      - echo "web: dotnet AWSCodePipelineDemo.dll --urls http://0.0.0.0:5000" > ./publish_output/Procfile
artifacts:
  files:
    - '**/*'
  base-directory: publish_output