version: 0.2
phases:
  install:
    commands:
      # Завантажуємо та встановлюємо .NET 9 вручну за допомогою офіційного скрипта Microsoft
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      # Додаємо встановлений .NET до змінних середовища
      - export PATH="$PATH:$HOME/.dotnet"
      - export DOTNET_ROOT="$HOME/.dotnet"
  build:
    commands:
      - dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
      - dotnet build AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
artifacts:
  files:
    - '**/*'